### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/as3-alexa#1]
Where are the environment variables set to define BIG-IP IP, etc.? Also, what are the vars required?

In the Alexa Developer Console > click Test > type in invocation "Application Services", and I get “Application Services is ready, ...“ so I think the interaction model and Lambda is set up correctly.
However, when I try the  "create a service" intent, I enter in service name like HTTP1, and url site1.example.com and get:

`There was a problem with the requested skill's response`

Repro steps:
1. Copy alexaAs3Skill.json to new custom skill
2. Set up Lambda with the Alexa Skills kit  trigger and js files in below dir:
https://github.com/f5devcentral/as3-alexa/tree/master/lambda/as3AlexaLib 
3. Test skill in developer console

**Comment by tkam8** [comment]
I think I've found it in index.js where line 230 specifies the host
`hs.execute('CREATE', request, Config.host, (err, res, body) => {`

that should be calling lambda environment variables in Config.js using process.env

`Config.host = process.env.VE_MGMT_IP;`

So I went ahead and defined VE_MGMT_IP in lambda. 
**However**, I am now getting below after entering the service name and URL

`There was a problem with the requested skill's response`

CloudWatch logs for my lambda function show:

> 2018-09-17T13:45:25.468Z	eddaeaa9-ba7f-	{ VE_MGMT_IP: 'x.x.x.x',
PATH: '/var/lang/bin:/usr/local/bin:/usr/bin/:/bin',
LANG: 'en_US.UTF-8',
TZ: ':UTC',
LD_LIBRARY_PATH: '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib',
LAMBDA_TASK_ROOT: '/var/task',
LAMBDA_RUNTIME_DIR: '/var/runtime',
AWS_REGION: 'us-east-1',
AWS_DEFAULT_REGION: 'us-east-1',
AWS_LAMBDA_LOG_GROUP_NAME: '/aws/lambda/snoTk1',
AWS_LAMBDA_LOG_STREAM_NAME: '2018/09/17/[$LATEST]',
AWS_LAMBDA_FUNCTION_NAME: 'snoTk1',
AWS_LAMBDA_FUNCTION_MEMORY_SIZE: '128',
AWS_LAMBDA_FUNCTION_VERSION: '$LATEST',
_AWS_XRAY_DAEMON_ADDRESS: '169.254.79.2',
_AWS_XRAY_DAEMON_PORT: '2000',
AWS_XRAY_DAEMON_ADDRESS: '169.254.79.2:2000',
AWS_XRAY_CONTEXT_MISSING: 'LOG_ERROR',
_X_AMZN_TRACE_ID: 'Root=1-5b9faff4-b37358;Parent=2d2;Sampled=0',
AWS_EXECUTION_ENV: 'AWS_Lambda_nodejs6.10',
_HANDLER: 'index.handler',
NODE_PATH: '/var/runtime:/var/task:/var/runtime/node_modules',
AWS_ACCESS_KEY_ID: 'omitted',
AWS_SECRET_ACCESS_KEY: 'omitted',
AWS_SESSION_TOKEN: 'omitted',
NODE_TLS_REJECT_UNAUTHORIZED: '0' }

and after that one:
>2018-09-17T13:45:25.526Z	eddaeaa9-ba7f	Service {
config: 
Config {
credentials: 
EnvironmentCredentials {
expired: false,
expireTime: null,
accessKeyId: 'omitted',
sessionToken: 'omitted',
envPrefix: 'AWS' },
credentialProvider: CredentialProviderChain { providers: [Object] },
region: 'us-west-2',
logger: null,
apiVersions: {},
apiVersion: null,
endpoint: 'lambda.us-west-2.amazonaws.com',
httpOptions: { timeout: 120000 },
maxRetries: undefined,
maxRedirects: 10,
paramValidation: true,
sslEnabled: true,
s3ForcePathStyle: false,
s3BucketEndpoint: false,
s3DisableBodySigning: true,
computeChecksums: true,
convertResponseTypes: true,
correctClockSkew: false,
customUserAgent: null,
dynamoDbCrc32: true,
systemClockOffset: 0,
signatureVersion: 'v4',
signatureCache: true,
retryDelayOptions: {},
useAccelerateEndpoint: false },
isGlobalEndpoint: false,
endpoint: 
Endpoint {
protocol: 'https:',
host: 'lambda.us-west-2.amazonaws.com',
port: 443,
hostname: 'lambda.us-west-2.amazonaws.com',
pathname: '/',
path: '/',
href: 'https://lambda.us-west-2.amazonaws.com/' },
_clientId: 2 }



any ideas?
what is the "URL" I should be entering? (url_param intent)...is this the service that is to be fronted by F5? 
It looks like the app_name intent is the name used for creating the F5 service (virtual server).

**Comment by adam-f5** [comment]
Repository Archived
